# Generated by Django 5.2.8 on 2025-12-02 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del flujo')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WEBHOOK', 'Webhook Trigger'), ('HTTP_REQUEST', 'Petición HTTP'), ('CONDITION', 'Condición Lógica'), ('EMAIL', 'Enviar Email')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('ui_position', models.JSONField(default=dict, help_text='Coordenadas {x: 100, y: 200}')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('target_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='automation.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='automation.node')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.workflow')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
